export const courses = [
  {
    "id": 1541,
    "availability": "19",
    "enrollment": 1,
    "coursenum": "CSC 8000",
    "coursename": "THESIS RESEARCH",
    "type": "Res",
    "section": 2,
    "credits": "1-12",
    "time": "TBA",
    "days": "TBA",
    "building": "",
    "instructor": "WANG C",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": "Permission of department.",
    "notes": "“S”/”U” grading.",
    "description": null
  },
  {
    "id": 2134,
    "availability": "95",
    "enrollment": 4,
    "coursenum": "CSC 9000",
    "coursename": "DISSERTATION RES",
    "type": "Res",
    "section": 10,
    "credits": "1-12",
    "time": "TBA",
    "days": "TBA",
    "building": "",
    "instructor": "BAUMGARTNER G",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": "",
    "notes": "“S”/”U” grading.",
    "description": null
  },
  {
    "id": 4722,
    "availability": "4",
    "enrollment": 1,
    "coursenum": "CSC 4999",
    "coursename": "ADV IND UNDERGRAD RES",
    "type": "Res",
    "section": 1,
    "credits": "1-3",
    "time": "TBA",
    "days": "TBA",
    "building": "",
    "instructor": "BRANDT S",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": "Consent of department chair. ",
    "notes": "May be taken for a max. of 4 hrs. of credit.",
    "description": "Individual readings, conferences and program development in computer science."
  },
  {
    "id": 5008,
    "availability": "98",
    "enrollment": 1,
    "coursenum": "CSC 7999",
    "coursename": "SEL READINGS IN CSC",
    "type": "Res",
    "section": 6,
    "credits": "1-3",
    "time": "TBA",
    "days": "TBA",
    "building": "",
    "instructor": "PARK S",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": "Consent of department.",
    "notes": "“S”/”U” grading. May be taken for a max. of 6 sem. hrs. of credit.",
    "description": null
  },
  {
    "id": 5892,
    "availability": "18",
    "enrollment": 2,
    "coursenum": "CSC 7090",
    "coursename": "DESIGN PROJECT",
    "type": "Ind",
    "section": 7,
    "credits": "1-9",
    "time": "TBA",
    "days": "TBA",
    "building": "",
    "instructor": "KARKI",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": "Permission of department.",
    "notes": "S/U grading. ",
    "description": "Individual design, development, implementation, and documentation of a computer science project addressing a problem in the student’s specialization. "
  },
  {
    "id": 6241,
    "availability": "98",
    "enrollment": 1,
    "coursenum": "CSC 9000",
    "coursename": "DISSERTATION RES",
    "type": "Res",
    "section": 9,
    "credits": "1-12",
    "time": "TBA",
    "days": "TBA",
    "building": "",
    "instructor": "CHEN F",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": null,
    "notes": "“S”/”U” grading.",
    "description": null
  },
  {
    "id": 6724,
    "availability": "14",
    "enrollment": 34,
    "coursenum": "CSC 4610",
    "coursename": "CLD SYSTMS & VRTLZN",
    "type": "Lec",
    "section": 1,
    "credits": "3",
    "time": "130-0250",
    "days": "M W",
    "building": "2324 PATRICK TAYLOR",
    "instructor": "WANG Q",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": null,
    "prereqs": "CSC 2610, CSC 4103, and credit or registration in CSC 4501.",
    "notes": null,
    "description": "Advanced problems and challenges in defining, developing, and building a cloud system; virtualization; open source computing; provisioning; fairness, reliability, security, and monitoring."
  },
  {
    "id": 7005,
    "availability": "(F)",
    "enrollment": 35,
    "coursenum": "CSC 4890",
    "coursename": "INTR THEORY COMPUTAT",
    "type": "Lec",
    "section": 1,
    "credits": "3",
    "time": "130-0250",
    "days": "T TH",
    "building": "TRIANTAPHYLLO\n",
    "instructor": "TRIANTAPHYLLO",
    "moreinfo": "WORLD WIDE WEB-BASED DELIVERY",
    "specialenrollment": "100% WEB BASED",
    "lab": null,
    "prereqs": "CSC 2259",
    "notes": null,
    "description": "Introduction to finite automata, regular expressions and languages; push-down automata and context-free languages; selected advanced language theoretical topics; emphasis on technique."
  },
  {
    "id": 7804,
    "availability": "36",
    "enrollment": 44,
    "coursenum": "CSC 2262",
    "coursename": "NUMERICAL METHODS",
    "type": "Lec",
    "section": 1,
    "credits": "3",
    "time": "900-1020",
    "days": "T TH",
    "building": "1245 PATRICK TAYLOR",
    "instructor": "BRENER N",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": null,
    "prereqs": "CSC 1254 or CSC 1351, and credit or registration in MATH 2090.",
    "notes": "Credit will be given for only one of the following: CSC 1240, 2262, CSC 2533 or IE 2060. ",
    "description": "Computer- oriented methods for solving numerical problems in science and engineering; numerical solutions to systems of simultaneous linear equations, nonlinear algebraic equations (root solving), differentiation and integration, ordinary differential equations, interpolation and curve fitting."
  },
  {
    "id": 11070,
    "availability": "98",
    "enrollment": 1,
    "coursenum": "CSC 9000",
    "coursename": "DISSERTATION RES",
    "type": "Res",
    "section": 17,
    "credits": "1-12",
    "time": "TBA",
    "days": "TBA",
    "building": "",
    "instructor": "TRIANTAPHYLLO\n",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": null,
    "notes": "“S”/”U” grading.",
    "description": null
  },
  {
    "id": 13077,
    "availability": "3",
    "enrollment": 45,
    "coursenum": "CSC 4356",
    "coursename": "INTER COMP GRPHCS",
    "type": "Lec",
    "section": 1,
    "credits": "3",
    "time": "1030-1150",
    "days": "T TH",
    "building": "1240 PATRICK TAYLOR",
    "instructor": "KARKI B",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": null,
    "prereqs": "CSC 3102",
    "notes": null,
    "description": "Analytical treatment of computer graphics; graphical display and input devices; computer graphics systems and standards; three-dimensional transformations; geometric modeling; lighting; shading; interaction; basic data structures; realism in 3D graphics; future trends. "
  },
  {
    "id": 13196,
    "availability": "37",
    "enrollment": 88,
    "coursenum": "CSC 4101",
    "coursename": "PROG LANGUAGES",
    "type": "Lec",
    "section": 1,
    "credits": "3",
    "time": "300-0420",
    "days": "M W",
    "building": "1263 PATRICK TAYLOR",
    "instructor": "BAUMGARTNER G",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": null,
    "prereqs": "CSC 3102",
    "notes": null,
    "description": "Principles of programming language design; specification of syntax and semantics; underlying implementation of block structured languages; dynamic memory allocation for strings, lists and arrays; imperative versus applicative programming; logic programming; modern programming languages."
  },
  {
    "id": 13309,
    "availability": "4",
    "enrollment": 1,
    "coursenum": "CSC 4999",
    "coursename": "ADV IND UNDERGRAD RES",
    "type": "Res",
    "section": 3,
    "credits": "1-3",
    "time": "TBA",
    "days": "TBA",
    "building": "",
    "instructor": "WEBB A",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": "Consent of department chair. ",
    "notes": "May be taken for a max. of 4 hrs. of credit.",
    "description": "Individual readings, conferences and program development in computer science."
  },
  {
    "id": 13356,
    "availability": "18",
    "enrollment": 2,
    "coursenum": "CSC 7090",
    "coursename": "DESIGN PROJECT",
    "type": "Ind",
    "section": 6,
    "credits": "1-9",
    "time": "TBA",
    "days": "TBA",
    "building": "",
    "instructor": "WANG",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": "Permission of department.",
    "notes": "S/U grading. ",
    "description": "Individual design, development, implementation, and documentation of a computer science project addressing a problem in the student’s specialization. "
  },
  {
    "id": 14011,
    "availability": "18",
    "enrollment": 7,
    "coursenum": "CSC 7740",
    "coursename": "BIG DATA SYS & APP",
    "type": "Lec",
    "section": 2,
    "credits": "3",
    "time": "TBA",
    "days": "TBA",
    "building": "",
    "instructor": "LEE K",
    "moreinfo": "WORLD WIDE WEB-BASED DELIVERY",
    "specialenrollment": "100% WEB BASED",
    "lab": null,
    "prereqs": "CSC 4103 and CSC 4402.",
    "notes": null,
    "description": "Principles, techniques, and systems for big data processing; Hadoop, Spark, and NoSQL ecosystems; application development using big data systems."
  },
  {
    "id": 14019,
    "availability": "4",
    "enrollment": 1,
    "coursenum": "CSC 7999",
    "coursename": "SEL READINGS IN CSC",
    "type": "Res",
    "section": 2,
    "credits": "1-3",
    "time": "TBA",
    "days": "TBA",
    "building": "",
    "instructor": "MAHMOUD A",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": "Consent of department.",
    "notes": "“S”/”U” grading. May be taken for a max. of 6 sem. hrs. of credit.",
    "description": null
  },
  {
    "id": 14257,
    "availability": "96",
    "enrollment": 3,
    "coursenum": "CSC 9000",
    "coursename": "DISSERTATION RES",
    "type": "Res",
    "section": 2,
    "credits": "1-12",
    "time": "TBA",
    "days": "TBA",
    "building": "",
    "instructor": "WANG C",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": null,
    "notes": "“S”/”U” grading.",
    "description": null
  },
  {
    "id": 14854,
    "availability": "13",
    "enrollment": 3,
    "coursenum": "CSC 2700",
    "coursename": "COMP SCI TEACH MTHDS",
    "type": "Lec",
    "section": 2,
    "credits": "1-3",
    "time": "330-0450",
    "days": "M W",
    "building": "136 PRESCOTT",
    "instructor": "ALEGRE F",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": null,
    "prereqs": "CSC 1254 or CSC 1351 or permission of department.",
    "notes": "May be taken for a max. of 6 hrs. of credit when topics vary. Total credit earned in CSC 2700 and CSC 4700 should not exceed 9 hrs.",
    "description": "Specialized areas of current interest in computer science."
  },
  {
    "id": 17538,
    "availability": "(F)",
    "enrollment": 96,
    "coursenum": "CSC 1351",
    "coursename": "COMP SCI II-MJRS",
    "type": "Lec",
    "section": 1,
    "credits": "4",
    "time": "1030-1150",
    "days": "T TH",
    "building": "1225 PATRICK TAYLOR",
    "instructor": "MAHMOUD A",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": null,
    "prereqs": "CSC 1350; credit or registration in MATH 1550. Credit will not be given for both this course and CSC 1254",
    "notes": "Credit will not be given for both this course and CSC 1254. 3 hrs. lecture; 3 hrs. lab.",
    "description": "Develops solutions to problems using an object-oriented approach and emphasizes the concepts of recursion; dynamic memory; data structures (lists, stacks, queues, trees); exception handling."
  },
  {
    "id": 19110,
    "availability": "2",
    "enrollment": 3,
    "coursenum": "CSC 4999",
    "coursename": "ADV IND UNDERGRAD RES",
    "type": "Res",
    "section": 2,
    "credits": "1-3",
    "time": "TBA",
    "days": "TBA",
    "building": "",
    "instructor": "MAHMOUD A",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": "Consent of department chair. ",
    "notes": "May be taken for a max. of 4 hrs. of credit.",
    "description": "Individual readings, conferences and program development in computer science."
  },
  {
    "id": 19547,
    "availability": "9",
    "enrollment": 15,
    "coursenum": "CSC 7442",
    "coursename": "DATA MINING KNOW DEV",
    "type": "Lec",
    "section": 1,
    "credits": "3",
    "time": "1030-1150",
    "days": "T TH",
    "building": "",
    "instructor": "TRIANTAPHYLLO\n",
    "moreinfo": "WORLD WIDE WEB-BASED DELIVERY",
    "specialenrollment": "100% WEB BASED",
    "lab": null,
    "prereqs": "CSC 7333.",
    "notes": null,
    "description": "Introduction to data mining and knowledge discovery in databases; data cleaning, statistical techniques, association rule learning; time series and spatial data mining algorithms, clustering algorithms, data visualization."
  },
  {
    "id": 19732,
    "availability": "2",
    "enrollment": 70,
    "coursenum": "CSC 4402",
    "coursename": "INTR DATABSE MGT SYS",
    "type": "Lec",
    "section": 1,
    "credits": "3",
    "time": "930-1050",
    "days": "M W",
    "building": "0120 TUREAUD HALL",
    "instructor": "CHEN J",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": null,
    "prereqs": "CSC 3102",
    "notes": null,
    "description": "Fundamentals of the relational data model; the SQL query language; E-R modeling and database design theory; storage structures and query optimization; transaction processing and concurrency control."
  },
  {
    "id": 20551,
    "availability": "19",
    "enrollment": 1,
    "coursenum": "CSC 7090",
    "coursename": "DESIGN PROJECT",
    "type": "Ind",
    "section": 4,
    "credits": "1-9",
    "time": "TBA",
    "days": "TBA",
    "building": "",
    "instructor": "LEE",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": "Permission of department.",
    "notes": "S/U grading. ",
    "description": "Individual design, development, implementation, and documentation of a computer science project addressing a problem in the student’s specialization. "
  },
  {
    "id": 20786,
    "availability": "98",
    "enrollment": 1,
    "coursenum": "CSC 9000",
    "coursename": "DISSERTATION RES",
    "type": "Res",
    "section": 16,
    "credits": "1-12",
    "time": "TBA",
    "days": "TBA",
    "building": "",
    "instructor": "CHEN J",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": null,
    "notes": "“S”/”U” grading.",
    "description": null
  },
  {
    "id": 21277,
    "availability": "97",
    "enrollment": 2,
    "coursenum": "CSC 3999",
    "coursename": "IND UNDERGRAD RES",
    "type": "Res",
    "section": 1,
    "credits": "1-3",
    "time": "TBA",
    "days": "TBA",
    "building": "TBA",
    "instructor": "BRANDT",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": "Consent of department chair.",
    "notes": "May be taken for a max. of 4 hrs. of credit.",
    "description": "Individual readings, conferences and program development in computer science."
  },
  {
    "id": 21770,
    "availability": "(F)",
    "enrollment": 131,
    "coursenum": "CSC 1350",
    "coursename": "COMP SCI I-MJRS",
    "type": "Lec",
    "section": 1,
    "credits": "4",
    "time": "1030-1120",
    "days": "M W F",
    "building": "1200 PATRICK TAYLOR",
    "instructor": "AYMOND P",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": {
      "id": 8532,
      "type": "Lab",
      "labtime": "430-0720N",
      "labdays": "TH",
      "labinstructor": "AYMOND P"
    },
    "prereqs": "Credit or registration in MATH 1022 or MATH 1023 or MATH 1550 or MATH 1551 or MATH 1552.",
    "notes": "Credit will not be given for both this course and CSC 1250 or CSC 1253. 3 hrs. lecture; 3 hrs. lab. ",
    "description": " Fundamentals of algorithm development, program design and structured programming using an object-oriented language."
  },
  {
    "id": 21852,
    "availability": "(F)",
    "enrollment": 61,
    "coursenum": "CSC 4103",
    "coursename": "OPERATING SYSTEMS",
    "type": "Lec",
    "section": 1,
    "credits": "3",
    "time": "130-0250",
    "days": "M W",
    "building": "1225 PATRICK TAYLOR",
    "instructor": "RICHARD G",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": null,
    "prereqs": "CSC 3102",
    "notes": null,
    "description": "Design techniques, process management, processor scheduling; deadlocks, memory management, secondary memory management, file management; I/O systems, Unix systems."
  },
  {
    "id": 23330,
    "availability": "97",
    "enrollment": 2,
    "coursenum": "CSC 9000",
    "coursename": "DISSERTATION RES",
    "type": "Res",
    "section": 1,
    "credits": "1-12",
    "time": "TBA",
    "days": "TBA",
    "building": "",
    "instructor": "MUKHOPADHYAY\n",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": null,
    "notes": "“S”/”U” grading.",
    "description": null
  },
  {
    "id": 23578,
    "availability": "4",
    "enrollment": 1,
    "coursenum": "CSC 4999",
    "coursename": "ADV IND UNDERGRAD RES",
    "type": "Res",
    "section": 4,
    "credits": "1-3",
    "time": "TBA",
    "days": "TBA",
    "building": "",
    "instructor": "GLASS C",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": "Consent of department chair. ",
    "notes": "May be taken for a max. of 4 hrs. of credit.",
    "description": "Individual readings, conferences and program development in computer science."
  },
  {
    "id": 24768,
    "availability": "3",
    "enrollment": 93,
    "coursenum": "CSC 2362",
    "coursename": "INTRO TO CYBERSECUR",
    "type": "Lec",
    "section": 1,
    "credits": "3",
    "time": "1030-1150",
    "days": "T TH",
    "building": "1221 PATRICK TAYLOR",
    "instructor": "GLASS C",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": null,
    "prereqs": "CSC 1350 or CSC 1253 or equivalent.",
    "notes": null,
    "description": "Broad overview and basic principles of cybersecurity theory and practice: threats, vulnerabilities, and mitigation strategies."
  },
  {
    "id": 25228,
    "availability": "4",
    "enrollment": 78,
    "coursenum": "CSC 4243",
    "coursename": "INTERFACE DESGN TECH",
    "type": "Lec",
    "section": 1,
    "credits": "3",
    "time": "900-1020",
    "days": "T TH",
    "building": "1206 PATRICK TAYLOR",
    "instructor": "WEBB A",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": null,
    "prereqs": "CSC 1253 or CSC 1350 or equivalent programming background.",
    "notes": null,
    "description": "Human-computer interaction provides the bridges across which humans engage with computation. An overview and experience with the design of such interfaces. Programming and design projects employing both traditional graphical interfaces; handheld graphical interfaces; and tangible and embedded interfaces. All programming in Java languages."
  },
  {
    "id": 25472,
    "availability": "1",
    "enrollment": 91,
    "coursenum": "CSC 4501",
    "coursename": "COMPUTER NETWORKS",
    "type": "Lec",
    "section": 1,
    "credits": "3",
    "time": "1200-0120",
    "days": "T TH",
    "building": "1225 PATRICK TAYLOR",
    "instructor": "WANG H",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": null,
    "prereqs": "CSC 3102",
    "notes": null,
    "description": "Introduction to local, metropolitan and wide area networks using the standard OSI reference model as a framework; introduction to the Internet protocol suite and network tools and programming; discussion of various networking technologies."
  },
  {
    "id": 26168,
    "availability": "96",
    "enrollment": 3,
    "coursenum": "CSC 3999",
    "coursename": "IND UNDERGRAD RES",
    "type": "Res",
    "section": 3,
    "credits": "1-3",
    "time": "TBA",
    "days": "TBA",
    "building": "TBA",
    "instructor": "RICHARD",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": null,
    "prereqs": "Consent of department chair.",
    "notes": "May be taken for a max. of 4 hrs. of credit.",
    "description": "Individual readings, conferences and program development in computer science."
  },
  {
    "id": 28408,
    "availability": "(F)",
    "enrollment": 48,
    "coursenum": "CSC 2730",
    "coursename": "DATA SCI & ANALYTICS",
    "type": "Lec",
    "section": 1,
    "credits": "3",
    "time": "130-0250",
    "days": "T TH",
    "building": "2324 PATRICK TAYLOR",
    "instructor": "ZHANG J",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": null,
    "prereqs": "CSC 1254 or CSC 1351 or ISDS 3107.",
    "notes": null,
    "description": "Effective and efficient strategies for data capture; the relational database model, queries, and web programming; data mining and data warehousing process; descriptive statistics and visualization techniques; introduction to computational analysis and multidimensional analysis."
  },
  {
    "id": 28580,
    "availability": "2",
    "enrollment": 94,
    "coursenum": "CSC 1350",
    "coursename": "COMP SCI I-MJRS",
    "type": "Lec",
    "section": 2,
    "credits": "4",
    "time": "930-1020",
    "days": "M W F",
    "building": "1225 PATRICK TAYLOR",
    "instructor": "DONZE D",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": {
      "id": 4358,
      "type": "Lab",
      "labtime": "500-0750N",
      "labdays": "M",
      "labinstructor": "DONZE D"
    },
    "prereqs": "Credit or registration in MATH 1022 or MATH 1023 or MATH 1550 or MATH 1551 or MATH 1552.",
    "notes": "Credit will not be given for both this course and CSC 1250 or CSC 1253. 3 hrs. lecture; 3 hrs. lab. ",
    "description": " Fundamentals of algorithm development, program design and structured programming using an object-oriented language."
  },
  {
    "id": 29684,
    "availability": "(F)",
    "enrollment": 92,
    "coursenum": "CSC 3200",
    "coursename": "ETHICS IN COMPUTING",
    "type": "Lec",
    "section": 1,
    "credits": "1",
    "time": "1130-1220",
    "days": "M",
    "building": "0204 TUREAUD HALL",
    "instructor": "CARVER D",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": null,
    "prereqs": "ENGL 1005 or ENGL 2000 or HNRS 2000; CSC 3102.",
    "notes": "For majors only.",
    "description": "Introduction to ethics theory, ethical decision-making as it relates to the computing professional, licensing, intellectual property, conflicts of interest, freedom of information and privacy, security."
  },
  {
    "id": 30426,
    "availability": "3",
    "enrollment": 2,
    "coursenum": "CSC 3999",
    "coursename": "IND UNDERGRAD RES",
    "type": "Res",
    "section": 2,
    "credits": "1-3",
    "time": "TBA",
    "days": "TBA",
    "building": "TBA",
    "instructor": "WEBB",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": "Consent of department chair.",
    "notes": "May be taken for a max. of 4 hrs. of credit.",
    "description": "Individual readings, conferences and program development in computer science."
  },
  {
    "id": 32603,
    "availability": "13",
    "enrollment": 2,
    "coursenum": "CSC 4700",
    "coursename": "TRENDS IN CYB FORENS",
    "type": "Lec",
    "section": 1,
    "credits": "3",
    "time": "900-1020",
    "days": "T TH",
    "building": "1218 PATRICK TAYLOR",
    "instructor": "BAGGILI I",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": null,
    "prereqs": "CSC 3102 or permission of department. ",
    "notes": "May be taken for a max. of 9 cr. hrs. when topics vary. Total hrs. earned in CSC 2700 and 4700 should not exceed 9 hrs.",
    "description": "Specialized areas of current interest in computer science."
  },
  {
    "id": 33248,
    "availability": "25",
    "enrollment": 80,
    "coursenum": "CSC 3501",
    "coursename": "COMP ORGANIZATN/DSN",
    "type": "Lec",
    "section": 1,
    "credits": "3",
    "time": "130-0250",
    "days": "T TH",
    "building": "1263 PATRICK TAYLOR",
    "instructor": "LEE K",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": null,
    "prereqs": "CSC 2259.",
    "notes": "Credit will not be given for both this course and EE 3755.",
    "description": "Computer arithmetic, design of high-speed adders and multipliers, CPU concepts, instruction fetching and decoding, hardwired control, microprogramming control, main memory, I/O organization, assembly language programming techniques, CPU instruction sets and addressing modes."
  },
  {
    "id": 33611,
    "availability": "8",
    "enrollment": 97,
    "coursenum": "CSC 4444",
    "coursename": "ARTIFICIAL INTELLIG",
    "type": "Lec",
    "section": 1,
    "credits": "3",
    "time": "1200-0120",
    "days": "M W",
    "building": "1100 PATRICK TAYLOR",
    "instructor": "CHEN J",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": null,
    "prereqs": "CSC 3102",
    "notes": null,
    "description": "Theorem proving and inferencing techniques, production systems, knowledge representation, approximate reasoning, nonmonotonic reasoning, natural language understanding, scene analysis, planning, game playing and learning."
  },
  {
    "id": 34438,
    "availability": "98",
    "enrollment": 1,
    "coursenum": "CSC 9000",
    "coursename": "DISSERTATION RES",
    "type": "Res",
    "section": 4,
    "credits": "1-12",
    "time": "TBA",
    "days": "TBA",
    "building": "",
    "instructor": "MAHMOUD A",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": null,
    "notes": "“S”/”U” grading.",
    "description": null
  },
  {
    "id": 35310,
    "availability": "97",
    "enrollment": 2,
    "coursenum": "CSC 9000",
    "coursename": "DISSERTATION RES",
    "type": "Res",
    "section": 15,
    "credits": "1-12",
    "time": "TBA",
    "days": "TBA",
    "building": "",
    "instructor": "KARKI B",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": null,
    "notes": "“S”/”U” grading.",
    "description": null
  },
  {
    "id": 35458,
    "availability": "96",
    "enrollment": 3,
    "coursenum": "CSC 9000",
    "coursename": "DISSERTATION RES",
    "type": "Res",
    "section": 3,
    "credits": "1-12",
    "time": "TBA",
    "days": "TBA",
    "building": "",
    "instructor": "RICHARD G",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": null,
    "notes": "“S”/”U” grading.",
    "description": null
  },
  {
    "id": 35709,
    "availability": "97",
    "enrollment": 2,
    "coursenum": "CSC 9000",
    "coursename": "DISSERTATION RES",
    "type": "Res",
    "section": 8,
    "credits": "1-12",
    "time": "TBA",
    "days": "TBA",
    "building": "",
    "instructor": "WANG H",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": null,
    "notes": "“S”/”U” grading.",
    "description": null
  },
  {
    "id": 36146,
    "availability": "4",
    "enrollment": 1,
    "coursenum": "CSC 7999",
    "coursename": "SEL READINGS IN CSC",
    "type": "Res",
    "section": 1,
    "credits": "1-3",
    "time": "TBA",
    "days": "TBA",
    "building": "",
    "instructor": "SUN M",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": "Consent of department.",
    "notes": "“S”/”U” grading. May be taken for a max. of 6 sem. hrs. of credit.",
    "description": null
  },
  {
    "id": 37320,
    "availability": "8",
    "enrollment": 12,
    "coursenum": "CSC 7800",
    "coursename": "CSC RESEARCH SEMINAR",
    "type": "Sem",
    "section": 1,
    "credits": "1",
    "time": "930-1020",
    "days": "M",
    "building": "117 TUREAUD HALL",
    "instructor": "CARVER D",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": null,
    "prereqs": null,
    "notes": "Pass-fail grading. May be taken for a max. of 2 hrs. of credit when topics vary.",
    "description": "Student presentations and discussions on research topics in computer science."
  },
  {
    "id": 39559,
    "availability": "2",
    "enrollment": 37,
    "coursenum": "CSC 4362",
    "coursename": "SW VULN AND EXPLOIT",
    "type": "Lec",
    "section": 1,
    "credits": "3",
    "time": "1000-1250",
    "days": "W",
    "building": "2317 PATRICK TAYLOR",
    "instructor": "RICHARD G",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": null,
    "prereqs": "CSC 4103 or equivalent.",
    "notes": null,
    "description": "Advanced topics in software vulnerabilities, software exploitation techniques, remote vs. local exploits, user-space and kernel-space exploit mitigation strategies."
  },
  {
    "id": 39616,
    "availability": "51",
    "enrollment": 29,
    "coursenum": "CSC 3304",
    "coursename": "INTRO TO SYSTM PROG",
    "type": "Lec",
    "section": 1,
    "credits": "3",
    "time": "430-0550N",
    "days": "T TH",
    "building": "1225 PATRICK TAYLOR",
    "instructor": "DONZE D",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": null,
    "prereqs": "Credit or registration in CSC 3102.",
    "notes": null,
    "description": "Introduction to systems programming, using the C programming language: OS command and shell basics, process creation and control, system calls, signals, concurrency and virtualization."
  },
  {
    "id": 41948,
    "availability": "69",
    "enrollment": 16,
    "coursenum": "CSC 1240",
    "coursename": "STATS & GRAPH MATLB",
    "type": "Lec",
    "section": 1,
    "credits": "3",
    "time": "1130-1220",
    "days": "M W",
    "building": "1225 PATRICK TAYLOR",
    "instructor": "BRENER N",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": {
      "id": 4652,
      "type": "Lab",
      "labtime": "1130-0120",
      "labdays": "F",
      "labinstructor": "BRENER N"
    },
    "prereqs": "MATH 1021 or placement in MATH 1022, MATH 1023, MATH 1431, MATH 1550 or MATH 1551",
    "notes": "Credit will not be given for both this course and CSC 2262 or CSC 2533 or OCS 2011. Not for degree credit for computer science majors. 2 hrs. lecture; 2 hrs. lab.",
    "description": " Introduction to MATLAB programming with applications in statistics and graphics."
  },
  {
    "id": 43658,
    "availability": "12",
    "enrollment": 88,
    "coursenum": "CSC 1350",
    "coursename": "COMP SCI I-MJRS",
    "type": "Lec",
    "section": 3,
    "credits": "4",
    "time": "130-0250",
    "days": "T TH",
    "building": "1125 BUS ED S WING",
    "instructor": "WALKER C",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": {
      "id": 9632,
      "type": "Lab",
      "labtime": "500-0750N",
      "labdays": "T",
      "labinstructor": "MAHMOUD A"
    },
    "prereqs": "Credit or registration in MATH 1022 or MATH 1023 or MATH 1550 or MATH 1551 or MATH 1552.",
    "notes": "Credit will not be given for both this course and CSC 1250 or CSC 1253. 3 hrs. lecture; 3 hrs. lab. ",
    "description": " Fundamentals of algorithm development, program design and structured programming using an object-oriented language."
  },
  {
    "id": 43760,
    "availability": "4",
    "enrollment": 21,
    "coursenum": "CSC 7103",
    "coursename": "ADV OPERATING SYSTMS",
    "type": "Lec",
    "section": 1,
    "credits": "3",
    "time": "500-0620N",
    "days": "T TH",
    "building": "1240 PATRICK TAYLOR",
    "instructor": "CHEN F",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": null,
    "prereqs": "CSC 4103",
    "notes": null,
    "description": "Concurrent programming: shared memory, communication and operation-oriented models; concurrent, distributed and network programming; distributed operating systems; synchronization and deadlock detection in distributed systems."
  },
  {
    "id": 45105,
    "availability": "6",
    "enrollment": 34,
    "coursenum": "CSC 7300",
    "coursename": "ALGORTHM DSGN & ANLY",
    "type": "Lec",
    "section": 1,
    "credits": "3",
    "time": "500-0750N",
    "days": "M",
    "building": "0100 TUREAUD HALL",
    "instructor": "SHAH R",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": null,
    "prereqs": null,
    "notes": null,
    "description": "Characteristics of an algorithm; problems of algorithm existence; the design, implementation and complexity of algorithms; algorithm case studies."
  },
  {
    "id": 46945,
    "availability": "30",
    "enrollment": 130,
    "coursenum": "CSC 3102",
    "coursename": "ADV DATA STRUCTURES",
    "type": "Lec",
    "section": 1,
    "credits": "3",
    "time": "900-1020",
    "days": "T TH",
    "building": "1100 PATRICK TAYLOR",
    "instructor": "DUNCAN W",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": null,
    "prereqs": "CSC 1254 or CSC 1351 and credit or concurrent enrollment in CSC 2259 or EE 2741.",
    "notes": null,
    "description": "Description and utilization of formal ADT representations, especially those on lists, sets, and graphs; time and space analysis of recursive and nonrecursive algorithms, including graph and sorting algorithms; algorithm design techniques."
  },
  {
    "id": 47184,
    "availability": "4",
    "enrollment": 1,
    "coursenum": "CSC 3991",
    "coursename": "CSC HONORS RESEARCH ",
    "type": "Res",
    "section": 2,
    "credits": "3",
    "time": "TBA",
    "days": "TBA",
    "building": "TBA",
    "instructor": "WEBB",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": "CSC 3102; consent of department; admittance to Upper Division Honors Program.",
    "notes": null,
    "description": "Individual research on problems in computer science."
  },
  {
    "id": 47713,
    "availability": "28",
    "enrollment": 87,
    "coursenum": "CSC 4330",
    "coursename": "SOFTWARE SYST DEVEL",
    "type": "Lec",
    "section": 1,
    "credits": "3",
    "time": "300-0420",
    "days": "T TH",
    "building": "1200 PATRICK TAYLOR",
    "instructor": "MAHMOUD A",
    "moreinfo": "SECTION INVOLVES COMMUNICATION-INTENSIVE LEARNING",
    "specialenrollment": "CI-WRITTEN&SPOK",
    "lab": null,
    "prereqs": "CSC 3102, CSC 3380.",
    "notes": null,
    "description": "Software requirements analysis; design representation, programming methodologies; verification, validation, maintenance and software planning."
  },
  {
    "id": 48315,
    "availability": "34",
    "enrollment": 46,
    "coursenum": "CSC 1253",
    "coursename": "COMP SCI WITH C++",
    "type": "Lec",
    "section": 2,
    "credits": "3",
    "time": "130-0250",
    "days": "T TH",
    "building": "1245 PATRICK TAYLOR",
    "instructor": "DUNCAN W",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": null,
    "prereqs": "Credit or registration in MATH 1550 or credit in MATH 1431.",
    "notes": "Credit will not be given for both this course and CSC 1250 or CSC 1350.",
    "description": "Fundamentals of algorithm development, program design and structured programming using an object-oriented language."
  },
  {
    "id": 49375,
    "availability": "98",
    "enrollment": 1,
    "coursenum": "CSC 9000",
    "coursename": "DISSERTATION RES",
    "type": "Res",
    "section": 12,
    "credits": "1-12",
    "time": "TBA",
    "days": "TBA",
    "building": "",
    "instructor": "LEE K",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": null,
    "notes": "“S”/”U” grading.",
    "description": null
  },
  {
    "id": 50187,
    "availability": "98",
    "enrollment": 1,
    "coursenum": "CSC 9000",
    "coursename": "DISSERTATION RES",
    "type": "Res",
    "section": 11,
    "credits": "1-12",
    "time": "TBA",
    "days": "TBA",
    "building": "",
    "instructor": "CARVER D",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": null,
    "notes": "“S”/”U” grading.",
    "description": null
  },
  {
    "id": 50723,
    "availability": "19",
    "enrollment": 1,
    "coursenum": "CSC 8000",
    "coursename": "THESIS RESEARCH",
    "type": "Res",
    "section": 4,
    "credits": "1-12",
    "time": "TBA",
    "days": "TBA",
    "building": "",
    "instructor": "RICHARD G",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": "Permission of department.",
    "notes": "“S”/”U” grading.",
    "description": null
  },
  {
    "id": 50835,
    "availability": "18",
    "enrollment": 162,
    "coursenum": "CSC 2259",
    "coursename": "DISCRETE STRUCTURES",
    "type": "Lec",
    "section": 1,
    "credits": "3",
    "time": "1200-0120",
    "days": "T TH",
    "building": "1100 PATRICK TAYLOR",
    "instructor": "SHAH R",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": null,
    "prereqs": "Credit or registration in CSC 1254 or CSC 1351 and MATH 1552.",
    "notes": "",
    "description": "Set algebra including mappings and relations; algebraic structures including semigroups and groups; elements of the theory of directed and undirected graphs; Boolean algebra and propositional logic; these structures applied to various areas of computer science."
  },
  {
    "id": 51981,
    "availability": "14",
    "enrollment": 11,
    "coursenum": "CSC 2700",
    "coursename": "CMPTVE PRGMG 1CR HR",
    "type": "Lec",
    "section": 1,
    "credits": "1-3",
    "time": "600-0750N",
    "days": "T",
    "building": "1216 PATRICK TAYLOR",
    "instructor": "TRAXLER I",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": null,
    "prereqs": "CSC 1254 or CSC 1351 or permission of department.",
    "notes": "May be taken for a max. of 6 hrs. of credit when topics vary. Total credit earned in CSC 2700 and CSC 4700 should not exceed 9 hrs.",
    "description": "Specialized areas of current interest in computer science."
  },
  {
    "id": 52334,
    "availability": "97",
    "enrollment": 2,
    "coursenum": "CSC 9000",
    "coursename": "DISSERTATION RES",
    "type": "Res",
    "section": 5,
    "credits": "1-12",
    "time": "TBA",
    "days": "TBA",
    "building": "",
    "instructor": "KAISER H",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": null,
    "notes": "“S”/”U” grading.",
    "description": null
  },
  {
    "id": 53592,
    "availability": "2",
    "enrollment": 82,
    "coursenum": "CSC 3380",
    "coursename": "OBJ ORIENTED DESIGN",
    "type": "Lec",
    "section": 1,
    "credits": "3",
    "time": "300-0420",
    "days": "T TH",
    "building": "1245 PATRICK TAYLOR",
    "instructor": "GLASS C",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": null,
    "prereqs": "CSC 1254 or CSC 1351.",
    "notes": null,
    "description": "Advanced object oriented software development; emphasis on the use of the unified modeling language as a design tool."
  },
  {
    "id": 53693,
    "availability": "96",
    "enrollment": 3,
    "coursenum": "CSC 9000",
    "coursename": "DISSERTATION RES",
    "type": "Res",
    "section": 14,
    "credits": "1-12",
    "time": "TBA",
    "days": "TBA",
    "building": "",
    "instructor": "WANG Q",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": null,
    "notes": "“S”/”U” grading.",
    "description": null
  },
  {
    "id": 55617,
    "availability": "7",
    "enrollment": 12,
    "coursenum": "CSC 7700",
    "coursename": "ADV TRENDS CYB & FOREN",
    "type": "Lec",
    "section": 2,
    "credits": "3",
    "time": "900-1020",
    "days": "T TH",
    "building": "1218 PATRICK TAYLOR",
    "instructor": "BAGGILI I",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": null,
    "prereqs": null,
    "notes": "May be taken for a max. of 12 hrs. of credit when topics vary. ",
    "description": "Specialized areas of current interest in computer science."
  },
  {
    "id": 57254,
    "availability": "98",
    "enrollment": 1,
    "coursenum": "CSC 9000",
    "coursename": "DISSERTATION RES",
    "type": "Res",
    "section": 7,
    "credits": "1-12",
    "time": "TBA",
    "days": "TBA",
    "building": "",
    "instructor": "WEBB A",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": null,
    "notes": "“S”/”U” grading.",
    "description": null
  },
  {
    "id": 57366,
    "availability": "14",
    "enrollment": 6,
    "coursenum": "CSC 7090",
    "coursename": "DESIGN PROJECT",
    "type": "Ind",
    "section": 1,
    "credits": "1-9",
    "time": "TBA",
    "days": "TBA",
    "building": "",
    "instructor": "CHEN",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": "Permission of department.",
    "notes": "S/U grading. ",
    "description": "Individual design, development, implementation, and documentation of a computer science project addressing a problem in the student’s specialization. "
  },
  {
    "id": 60728,
    "availability": "(F)",
    "enrollment": 50,
    "coursenum": "CSC 3730",
    "coursename": "MACHI LEARN & DATA",
    "type": "Lec",
    "section": 1,
    "credits": "3",
    "time": "1030-1150",
    "days": "T TH",
    "building": "2324 PATRICK TAYLOR",
    "instructor": "SUN M",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": null,
    "prereqs": "CSC 3102 and IE 3302 or EE 3150 or EXST 4050 or MATH 3355.",
    "notes": null,
    "description": "Machine learning principles and methods; advanced analytics for data; techniques for optimization and visualization; applications related to organizational performance and operational efficiency."
  },
  {
    "id": 61659,
    "availability": "8",
    "enrollment": 72,
    "coursenum": "CSC 1253",
    "coursename": "COMP SCI WITH C++",
    "type": "Lec",
    "section": 1,
    "credits": "3",
    "time": "1200-0120",
    "days": "T TH",
    "building": "1245 PATRICK TAYLOR",
    "instructor": "DUNCAN W",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": null,
    "prereqs": "Credit or registration in MATH 1550 or credit in MATH 1431.",
    "notes": "Credit will not be given for both this course and CSC 1250 or CSC 1350.",
    "description": "Fundamentals of algorithm development, program design and structured programming using an object-oriented language."
  },
  {
    "id": 61708,
    "availability": "97",
    "enrollment": 2,
    "coursenum": "CSC 9000",
    "coursename": "DISSERTATION RES",
    "type": "Res",
    "section": 13,
    "credits": "1-12",
    "time": "TBA",
    "days": "TBA",
    "building": "",
    "instructor": "SUN M",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": null,
    "notes": "“S”/”U” grading.",
    "description": null
  },
  {
    "id": 61885,
    "availability": "18",
    "enrollment": 2,
    "coursenum": "CSC 8000",
    "coursename": "THESIS RESEARCH",
    "type": "Res",
    "section": 3,
    "credits": "1-12",
    "time": "TBA",
    "days": "TBA",
    "building": "",
    "instructor": "KAISER H",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": "Permission of department.",
    "notes": "“S”/”U” grading.",
    "description": null
  },
  {
    "id": 62091,
    "availability": "19",
    "enrollment": 1,
    "coursenum": "CSC 7090",
    "coursename": "DESIGN PROJECT",
    "type": "Ind",
    "section": 5,
    "credits": "1-9",
    "time": "TBA",
    "days": "TBA",
    "building": "",
    "instructor": "SUN",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": "Permission of department.",
    "notes": "S/U grading. ",
    "description": "Individual design, development, implementation, and documentation of a computer science project addressing a problem in the student’s specialization. "
  },
  {
    "id": 62657,
    "availability": "19",
    "enrollment": 1,
    "coursenum": "CSC 3991",
    "coursename": "CSC HONORS RESEARCH ",
    "type": "Res",
    "section": 1,
    "credits": "3",
    "time": "TBA",
    "days": "TBA",
    "building": "TBA",
    "instructor": "RICHARD",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": "CSC 3102; consent of department; admittance to Upper Division Honors Program.",
    "notes": null,
    "description": "Individual research on problems in computer science."
  },
  {
    "id": 63245,
    "availability": "19",
    "enrollment": 1,
    "coursenum": "CSC 8000",
    "coursename": "THESIS RESEARCH",
    "type": "Res",
    "section": 1,
    "credits": "1-12",
    "time": "TBA",
    "days": "TBA",
    "building": "",
    "instructor": "BAUMGARTNER G",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": "Permission of department.",
    "notes": "“S”/”U” grading.",
    "description": null
  },
  {
    "id": 63822,
    "availability": "20",
    "enrollment": 10,
    "coursenum": "CSC 7360",
    "coursename": "MEMORY FORENSICS",
    "type": "Lec",
    "section": 1,
    "credits": "3",
    "time": "630-0750N",
    "days": "T TH",
    "building": "",
    "instructor": "SYLVE",
    "moreinfo": "WORLD WIDE WEB-BASED DELIVERY",
    "specialenrollment": "100% WEB BASED",
    "lab": null,
    "prereqs": "CSC 4103 or equivalent.",
    "notes": null,
    "description": "Memory acquisition strategies; operating systems internals; techniques for locating forensic artifacts in memory; application of memory forensics techniques to incident response, malware analysis, and traditional digital forensics investigations."
  },
  {
    "id": 63904,
    "availability": "97",
    "enrollment": 2,
    "coursenum": "CSC 9000",
    "coursename": "DISSERTATION RES",
    "type": "Res",
    "section": 6,
    "credits": "1-12",
    "time": "TBA",
    "days": "TBA",
    "building": "",
    "instructor": "ZHANG J",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": null,
    "notes": "“S”/”U” grading.",
    "description": null
  },
  {
    "id": 64102,
    "availability": "18",
    "enrollment": 2,
    "coursenum": "CSC 7090",
    "coursename": "DESIGN PROJECT",
    "type": "Ind",
    "section": 2,
    "credits": "1-9",
    "time": "TBA",
    "days": "TBA",
    "building": "",
    "instructor": "BAUMGARTNER",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": "Permission of department.",
    "notes": "S/U grading. ",
    "description": "Individual design, development, implementation, and documentation of a computer science project addressing a problem in the student’s specialization. "
  },
  {
    "id": 64561,
    "availability": "18",
    "enrollment": 2,
    "coursenum": "CSC 7090",
    "coursename": "DESIGN PROJECT",
    "type": "Ind",
    "section": 3,
    "credits": "1-9",
    "time": "TBA",
    "days": "TBA",
    "building": "",
    "instructor": "WANG",
    "moreinfo": "",
    "specialenrollment": "PERMIS OF DEPT",
    "lab": null,
    "prereqs": "Permission of department.",
    "notes": "S/U grading. ",
    "description": "Individual design, development, implementation, and documentation of a computer science project addressing a problem in the student’s specialization. "
  },
  {
    "id": 64829,
    "availability": "37",
    "enrollment": 11,
    "coursenum": "CSC 2730",
    "coursename": "DATA SCI & ANALYTICS",
    "type": "Lec",
    "section": 2,
    "credits": "3",
    "time": "300-0420",
    "days": "T TH",
    "building": "2324 PATRICK TAYLOR",
    "instructor": "ZHANG J",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": null,
    "prereqs": "CSC 1254 or CSC 1351 or ISDS 3107.",
    "notes": null,
    "description": "Effective and efficient strategies for data capture; the relational database model, queries, and web programming; data mining and data warehousing process; descriptive statistics and visualization techniques; introduction to computational analysis and multidimensional analysis."
  },
  {
    "id": 64857,
    "availability": "19",
    "enrollment": 6,
    "coursenum": "CSC 7700",
    "coursename": "CYBER-PHYSICAL SECUR",
    "type": "Lec",
    "section": 1,
    "credits": "3",
    "time": "900-1150",
    "days": "W",
    "building": "1835 BUS ED N WING",
    "instructor": "WANG C",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": null,
    "prereqs": null,
    "notes": "May be taken for a max. of 12 hrs. of credit when topics vary. ",
    "description": "Specialized areas of current interest in computer science."
  },
  {
    "id": 86455,
    "availability": "34",
    "enrollment": 36,
    "coursenum": "CSC 4103",
    "coursename": "OPERATING SYSTEMS",
    "type": "Lec",
    "section": 2,
    "credits": "3",
    "time": "130-0250",
    "days": "M W",
    "building": "E137 HOWE RUSSEL EA",
    "instructor": "ALI-GOMBE A",
    "moreinfo": "",
    "specialenrollment": "",
    "lab": null,
    "prereqs": "CSC 3102",
    "notes": null,
    "description": "Design techniques, process management, processor scheduling; deadlocks, memory management, secondary memory management, file management; I/O systems, Unix systems."
  }
]